### ISSUE TITLE
Using Audio-Only seems to use a lot of data

### ISSUE THREAD

**Issue by imBigo** [crackededed/Xtra#225]
It seems like using audio only should only download audio (well this is what I assumed happened) but I believe it just downloads source video and audio but just doesn't show video.
Would it be possible to have it only download audio?

**Comment by crackededed** [comment]
i assume you are using luminous proxy. luminous doesn't pass `allow_audio_only=true` to twitch and so we don't have an audio only track to play from. instead the current quality is used. you can switch to a lower quality then to audio only. in previous versions whatever was at the bottom of the quality menu was used. this issue could be fixed by modifying the luminous server to request for the audio only track

**Comment by crackededed** [comment]
https://github.com/AlyoshaVasilieva/luminous-ttv/issues/10
