### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by RileyOsno** [crackededed/Xtra#347]
The ability to support crackededed monetarily.

**Comment by tuxayo** [comment]
Ideas: [Liberapay](https://liberapay.com), it's libre and isn't subject to VAT (value added tax) since there are no counterparts in libre software projects, it works well with that. Patron on the other hand doesn't let choose to not have VAT even without counterparts.

People can even pledge to projects so if they join Liberapay it will start their recurring donations: https://liberapay.com/on/github/crackededed

~~Also [Bountysource](https://bountysource.com/), it could be advertised in the readme or issue template that you accept bounties. So people can pool money for a feature that would require a lot of work eventually giving a worthwhile incentive.~~ edit: Bountysource eventually got unsolvable and kept taking money until the last moment. Being bought by a crypto company didn't smell good.

**Comment by crackededed** [comment]
probably not doing that

**Comment by makeasnek** [comment]
Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues
