### ISSUE TITLE
No longer receiving channel points

### ISSUE THREAD

**Issue by qqawsedr8** [crackededed/Xtra#477]
I stopped receiving channel points all of a sudden no matter what app version I used. I hadn't touched any settings when this happened

**Comment by qqawsedr8** [comment]
Also my watch time isn't being tracked. For example if I do the !watchtime command for streamelements and again after some time, it remains the same as before.

**Comment by gnux922** [comment]
Hi ! I have the same problem, it started yesterday to not collect channel points. But, if I use the official Twitch app or the TwitchMod app, the points are being normally collected... so I started to think that it could be a problem of this app... but I cannot understand. At the moment, this is the only webpage that I found where this problem is mentioned. If anyone could help us... I am really fond of my channel points =)

**Comment by Tallefer** [comment]
well, I guess it's not just me then :) also started yesterday right after I updated the application, so I had to rollback two versions to check it more thoroughly before reporting here.
Also worth mentioning, it kinda half-works (only showing in chat that the points were collected) if you open the same channel in a browser at the same time and wait.

**Comment by crackededed** [comment]
fixed
