### ISSUE TITLE
certificate hash?

### ISSUE THREAD

**Issue by friendupright** [crackededed/Xtra#560]
I am looking for a certificate hash to verify the installation/apk.

Can you provide it so me and others can verify with appverifier.

Thanks :)

**Comment by crackededed** [comment]
app signing key is included in the source so isn't the hash useless?

**Comment by friendupright** [comment]
I'm not sure. I just want to be able to verify the apk by  certificate hash.

I'd be awesome if you could provide it.

**Comment by friendupright** [comment]
Can you?

**Comment by crackededed** [comment]
it's not going to verify anything. i guess you can still get it yourself if you really want to

**Comment by friendupright** [comment]
Newpipe does it too on there website. Please look into it :(

https://newpipe.net/#download

**Comment by crackededed** [comment]
it would require creating a new signing key. updates using a different signing key can't be installed without reinstalling the app. i don't think most people would want to reinstall for this

**Comment by friendupright** [comment]
I would since there's a backup and restore function. Would really appreciate it. I think others would too...

**Comment by KaiserCalm** [comment]
@crackededed I'd also really appreciate this feature as it ensures that I am downloading the correct apk.

I'm not an expert on this and I don't know how you're meant to get the signing key hash as the developer, but I had a thought. If you're compiling the app locally then immediatelly after compiling the app you could run what's mentioned on the [AppVerifier repo readme's Dowload section](https://github.com/soupslurpr/AppVerifier?tab=readme-ov-file#download) the `apksigner verify --print-certs app-release.apk` command and use the hash provided there.

I don't know if this is the best practice, but since you just compiled the application maybe it's fine?

The hash could then be listed in the readme.
